apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myapp
  namespace: monitoring
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: valerydubinin/diplom-app:1.0.0
      restartPolicy: Always
